# Node.js with React

trigger:
  batch: false
  branches:
    include:
      - main
      - master

#pr: none # will disable PR builds (but not CI builds)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: test
  jobs:
  - job: run_tests_job
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '10.x'

      - script: |
          npm install
        displayName: 'Install dependencies'

      - script: |
          npm run test a -- --watchAll=false --coverage
        displayName: 'Run tests'


- stage: build_and_publish
  # Run this stage if previous stage(s) succeeded and build reason ISN'T a pull request
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: build_and_publish_job
    continueOnError: 'false'
    steps:
      - script: |
          npm install
        displayName: 'Install dependencies'
        
      - script: |
          npm run build
        displayName: 'Build app'

      - task: CopyFiles@2
        displayName: 'Copy files'
        inputs:
          sourceFolder: 'build' 
          Contents: '**/*'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          cleanTargetFolder: true

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish app'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'